#!/usr/bin/env python3
"""Generate explanations for JLPT N2 Unit 9 (katakana loanwords)."""

import json, os

def E(label, definition):
    return (label, definition)

entries = [
    (791, "インテリア", "インテリア",
     "友だちの部屋はインテリアの趣味がいい。",
     "**My friend's room has good taste in interior decoration.**",
     [
         E("インテリア（インテリア）", "noun, \"interior furnishings, interior decor.\" From English \"interior.\" In Japanese, specifically refers to home furnishings and decorative items (furniture, lamps, curtains, etc.) rather than the interior space itself. Often used in compounds like インテリアショップ. [JLPT N2]"),
         E("趣味（しゅみ）", "noun, \"taste, aesthetic sense, hobby.\" Here refers to aesthetic judgment in decorating, not a personal hobby. 趣味がいい = \"has good taste\"; 趣味が悪い = \"has bad taste.\" [JLPT N4]"),
         E("〜は〜がいい", "pattern, \"X's Y is good.\" The topic は marks the domain of evaluation (the room), and the subject が marks the attribute being praised (taste). [JLPT N4]"),
     ]),
    (792, "コーナー", "コーナー",
     "冬になるとデパートにはお歳暮のコーナーが設けられる。",
     "**When winter comes, department stores set up a corner section for year-end gifts.**",
     [
         E("コーナー", "noun, \"corner, section, area.\" From English \"corner.\" In Japanese retail, refers to a designated section within a larger space dedicated to a specific product. Semantic narrowing: Japanese コーナー is more like a \"section\" than a physical corner. [JLPT N2]"),
         E("お歳暮（おせいぼ）", "noun, \"year-end gift.\" Traditional gift sent to express gratitude to someone who has helped you during the year. Delivered in December. Wago prefix お + kango 歳暮. [JLPT N2]"),
         E("〜になると", "pattern, \"when ~ comes.\" Indicates a seasonal or regular change. と marks a natural consequence. [JLPT N4]"),
         E("設けられる（もうけられる）", "他動詞 設ける（もうける）passive form, \"to be set up / established.\" Direct passive (not adversative). Counterpart 自動詞: 設かる is not used. [JLPT N2]"),
     ]),
    (793, "カウンター", "カウンター",
     "デパートには入口に案内のカウンターがある。",
     "**The department store has an information counter at the entrance.**",
     [
         E("カウンター", "noun, \"counter.\" From English \"counter.\" Refers to a long flat surface or desk where transactions or services take place. In retail: sales counter; in kitchens: countertop. [JLPT N2]"),
         E("入口（いりぐち）", "noun, \"entrance.\" 入る + 口. Contrast with 出口（でぐち）\"exit\" and 玄関（げんかん）\"main entrance (of a home).\" [JLPT N4]"),
         E("案内（あんない）", "kango noun, \"guidance, information.\" 案 (plan) + 内 (inside). 案内のカウンター = \"information counter.\" [JLPT N3]"),
         E("〜には〜がある", "pattern, \"in/at X there is Y.\" に marks location of existence, は topicalizes it. [JLPT N5]"),
     ]),
    (794, "スペース", "スペース",
     "部屋に大型テレビを置きたいが、スペースがない。",
     "**I want to put a large TV in the room, but there is no space.**",
     [
         E("スペース", "noun, \"space (physical area).\" From English \"space.\" Refers to room or physical area available. Distinct from 空間（くうかん）which is more abstract. [JLPT N2]"),
         E("大型（おおがた）", "kango noun, \"large-sized.\" 大 (big) + 型 (model/type). Used for objects: 大型テレビ, 大型バス. [JLPT N3]"),
         E("〜たいが", "pattern, \"want to ~ but.\" 〜たい expresses desire; が is adversative \"but\" introducing an obstacle. [JLPT N4]"),
         E("置く（おく）", "他動詞, \"to place, put.\" Counterpart 自動詞: 置かれる (passive). [JLPT N5]"),
     ]),
    (795, "オープン", "オープン",
     "駅前に新しいデパートがオープンした。",
     "**A new department store opened in front of the station.**",
     [
         E("オープン", "suru-verb / noun, \"opening (of a store/facility).\" From English \"open.\" More common in commercial contexts than 開店（かいてん）. Used intransitively here: the store opens (itself). [JLPT N2]"),
         E("駅前（えきまえ）", "noun, \"in front of the station.\" 駅 + 前. One of the most valuable commercial locations in Japan. [JLPT N4]"),
         E("〜がオープンした", "pattern, \"X opened.\" が marks the subject. オープンする as intransitive-use suru verb. [JLPT N2]"),
     ]),
    (796, "センター", "センター",
     "駅前のショッピングセンターで買い物をする。",
     "**I shop at the shopping center in front of the station.**",
     [
         E("ショッピングセンター", "compound noun, \"shopping center.\" ショッピング + センター. In Japan, often a multi-story building with various shops. [JLPT N2]"),
         E("〜で買い物をする", "pattern, \"to shop at (location).\" で marks the place where the action occurs. [JLPT N5]"),
     ]),
    (797, "カルチャー", "カルチャー",
     "外国の生活でカルチャーショックを受けることがある。",
     "**You can experience culture shock when living in a foreign country.**",
     [
         E("カルチャーショック", "compound noun, \"culture shock.\" カルチャー (culture) + ショック (shock). In Japanese, カルチャー alone can mean \"culture\" but ショック specifies the psychological impact. [JLPT N2]"),
         E("生活（せいかつ）", "kango noun, \"daily life, living.\" 生 (life) + 活 (activity). 外国の生活 = \"life in a foreign country.\" [JLPT N4]"),
         E("〜を受ける", "他動詞 受ける（うける）\"to receive / experience.\" Counterpart 自動詞: 受かる（うかる）has a different meaning (\"to pass an exam\"). Here: to receive/experience culture shock. [JLPT N4]"),
         E("ことがある", "pattern, \"sometimes / there are times when.\" Indicates that something can happen on occasion. [JLPT N4]"),
     ]),
    (798, "ブーム", "ブーム",
     "1960年代にフォークソングがブームになった。",
     "**Folk songs became a craze in the 1960s.**",
     [
         E("ブーム", "noun, \"boom, craze, fad.\" From English \"boom.\" In Japanese, specifically refers to a sudden surge of popularity — not an economic boom (which would be 景気拡大). 〜がブームになる is the standard collocation. [JLPT N2]"),
         E("1960年代（ねんだい）", "noun, \"the 1960s.\" 年代 = decade/era. [JLPT N4]"),
         E("フォークソング", "noun, \"folk song.\" From English \"folk song.\" Refers particularly to the Japanese folk music movement of the 1960s-70s. [JLPT N2]"),
         E("〜になる", "pattern, \"to become ~.\" ブームになった = \"became a craze / caught on.\" [JLPT N5]"),
     ]),
    (799, "インフォメーション", "インフォメーション",
     "駅には観光客用のインフォメーションデスクがある。",
     "**The station has an information desk for tourists.**",
     [
         E("インフォメーション", "noun, \"information.\" From English \"information.\" Often abbreviated to インフォ. In Japanese, typically refers to public information services rather than personal data. [JLPT N2]"),
         E("観光客（かんこうきゃく）", "kango noun, \"tourist.\" 観光 (sightseeing) + 客 (guest). 観光 itself derives from classical Chinese 観国之光. [JLPT N3]"),
         E("〜用（よう）", "suffix, \"for (purpose/use).\" 観光客用 = \"for tourists.\" [JLPT N3]"),
         E("デスク", "noun, \"desk.\" From English \"desk.\" In compounds: インフォメーションデスク, ヘルプデスク. [JLPT N2]"),
     ]),
    (800, "キャッチ", "キャッチ",
     "ボールをキャッチする。",
     "**Catch the ball.**",
     [
         E("キャッチ", "suru-verb / noun, \"to catch.\" From English \"catch.\" In Japanese, usually for catching physical objects. More casual than 捕まえる（つかまえる）. Compounds: キャッチボール (playing catch), キャッチコピー (catchphrase). [JLPT N2]"),
         E("ボール", "noun, \"ball.\" From English \"ball.\" [JLPT N5]"),
         E("〜をキャッチする", "pattern, \"to catch X.\" を marks the direct object. 他動詞 usage. [JLPT N2]"),
     ]),
]

batch2 = [
    (801, "メディア", "メディア",
     "今は、さまざまなメディアから情報を得ることができる。",
     "**Nowadays, you can obtain information from various media sources.**",
     [
         E("メディア", "noun, \"media.\" From English \"media\" (Latin medium = middle). In Japanese, treated as a collective noun for mass communication channels: TV, newspapers, internet, radio. [JLPT N2]"),
         E("さまざま（様々）", "na-adjective, \"various, diverse.\" Wago. Written in kana more often than kanji. さまざまなメディア. [JLPT N3]"),
         E("情報（じょうほう）", "kango noun, \"information.\" 情 (situation) + 報 (report). For Chinese speakers: Japanese 情報 covers both \"information\" and \"news/intelligence,\" broader than Chinese 情报. [JLPT N4]"),
         E("得（え）ることができる", "他動詞 得る（える/うる）potential form + ことができる, \"can obtain.\" 得る has two readings: える (modern) and うる (formal). No direct 自動詞 counterpart. [JLPT N3]"),
         E("〜から", "particle, \"from.\" Marks the source of information. [JLPT N5]"),
     ]),
    (802, "コメント", "コメント",
     "評論家がテレビで経済についてコメントしていた。",
     "**A critic was commenting on the economy on TV.**",
     [
         E("コメント", "noun / suru-verb, \"comment, remark.\" From English \"comment.\" Commonly used in media contexts. コメントする = to make a comment. More formal than 意見（いけん）in broadcast. [JLPT N2]"),
         E("評論家（ひょうろんか）", "kango noun, \"critic, commentator.\" 評論 (criticism) + 家 (specialist). [JLPT N2]"),
         E("経済（けいざい）", "kango noun, \"economy, economics.\" 経 (manage) + 済 (relieve). [JLPT N4]"),
         E("〜について", "pattern, \"about, concerning.\" Followed by a verb expressing discussion or thought. [JLPT N4]"),
         E("〜していた", "past progressive, \"was doing.\" Indicates an ongoing action observed in the past. [JLPT N4]"),
     ]),
    (803, "コラム", "コラム",
     "新聞や雑誌には多くのコラムがある。",
     "**Newspapers and magazines have many columns.**",
     [
         E("コラム", "noun, \"column (in newspaper/magazine).\" From English \"column.\" In Japanese media, a regular opinion piece or essay. Not the architectural column (柱・はしら). [JLPT N2]"),
         E("新聞（しんぶん）", "kango noun, \"newspaper.\" 新 (new) + 聞 (hear). [JLPT N5]"),
         E("雑誌（ざっし）", "kango noun, \"magazine.\" 雑 (miscellaneous) + 誌 (record). [JLPT N3]"),
         E("〜や〜には", "pattern, \"in things like X and Y.\" や is an incomplete list marker. [JLPT N4]"),
         E("多い（おおい）", "i-adjective, \"many, much.\" 多くのコラム. [JLPT N5]"),
     ]),
    (804, "エピソード", "エピソード",
     "日常生活のエピソードをエッセイに書く。",
     "**Write about episodes from daily life in an essay.**",
     [
         E("エピソード", "noun, \"episode, anecdote.\" From English \"episode.\" In Japanese, a short interesting personal story — not a TV episode (which would be 回). [JLPT N2]"),
         E("日常生活（にちじょうせいかつ）", "kango compound, \"daily life, everyday life.\" 日常 + 生活. [JLPT N3]"),
         E("エッセイ", "noun, \"essay.\" From English \"essay.\" In Japanese, usually a personal, informal essay (not academic). [JLPT N2]"),
         E("〜に書く", "pattern, \"to write in/on X.\" に marks the medium or destination. [JLPT N5]"),
     ]),
    (805, "アリバイ", "アリバイ",
     "彼には事件当日のアリバイがある。",
     "**He has an alibi for the day of the incident.**",
     [
         E("アリバイ", "noun, \"alibi.\" From English \"alibi\" (Latin \"elsewhere\"). Proof that someone was elsewhere when a crime occurred. Used in detective fiction and legal contexts. [JLPT N2]"),
         E("事件（じけん）", "kango noun, \"incident, case (esp. criminal).\" 事 + 件. Implies something serious vs. 事故 \"accident.\" [JLPT N3]"),
         E("当日（とうじつ）", "kango noun, \"that day, the day in question.\" 当 (that very) + 日. [JLPT N3]"),
         E("〜には〜がある", "pattern, \"X has Y.\" Literally \"as for X, Y exists.\" [JLPT N5]"),
     ]),
    (806, "シリーズ", "シリーズ",
     "この映画は、評判がよかったのでシリーズ化された。",
     "**This movie was made into a series because it was well received.**",
     [
         E("シリーズ", "noun, \"series.\" From English \"series.\" A sequence of related movies, books, etc. シリーズ化する = to turn into a series. [JLPT N2]"),
         E("映画（えいが）", "kango noun, \"movie, film.\" 映 (project) + 画 (picture). [JLPT N5]"),
         E("評判（ひょうばん）", "kango noun, \"reputation, reception.\" 評 (evaluate) + 判 (judge). 評判がよかった = \"was well received.\" [JLPT N3]"),
         E("〜化（か）された", "suffix 化 + passive された, \"was turned into.\" 化 is a productive suffix meaning \"to make into X.\" Passive because the movie received this action. [JLPT N2]"),
         E("〜ので", "conjunction, \"because, since.\" More explanatory/objective than から. [JLPT N4]"),
     ]),
    (807, "ポイント", "ポイント",
     "スクリーンのポイントを指しながら、プレゼンテーションをした。",
     "**While pointing at key points on the screen, I gave a presentation.**",
     [
         E("ポイント", "noun, \"key point, essential point.\" From English \"point.\" In business context, ポイント = \"key point to focus on.\" Also used for loyalty points (ポイントカード). [JLPT N2]"),
         E("スクリーン", "noun, \"screen.\" From English \"screen.\" Projection screen or digital display. [JLPT N2]"),
         E("指（さ）しながら", "他動詞 指す（さす）\"to point at\" + 〜ながら (while). 〜ながら indicates simultaneous actions. [JLPT N3]"),
         E("プレゼンテーション", "noun, \"presentation.\" From English \"presentation.\" Often abbreviated to プレゼン. [JLPT N2]"),
     ]),
    (808, "キー", "キー",
     "車のキーの中に入れたままロックしてしまった。",
     "**I accidentally locked the car with the key still inside.**",
     [
         E("キー", "noun, \"key.\" From English \"key.\" カギ (wago) and キー (katakana) are synonyms — キー sounds more modern/technical. [JLPT N2]"),
         E("車（くるま）", "noun, \"car, vehicle.\" Wago. [JLPT N5]"),
         E("〜入れたまま", "他動詞 入れる（いれる）\"to put in\" + 〜まま (leaving in that state). 入れる (他) ↔ 入る (自). [JLPT N3]"),
         E("ロックしてしまった", "noun / suru-verb ロックする \"to lock\" + 〜てしまった (regret). From English \"lock.\" 〜てしまった expresses regret about the accidental action. [JLPT N2]"),
     ]),
    (809, "マスター", "マスター",
     "独学で日本語をマスターした。",
     "**I mastered Japanese through self-study.**",
     [
         E("マスター", "suru-verb / noun, \"to master (a skill/language).\" From English \"master.\" Also means \"bar master/owner\" (pub master). Here: 他動詞 usage. [JLPT N2]"),
         E("独学（どくがく）", "kango noun, \"self-study.\" 独 (alone) + 学 (study). 独学で = \"through self-study\" — で marks the method. [JLPT N2]"),
         E("〜をマスターした", "pattern, \"mastered X.\" [JLPT N2]"),
     ]),
    (810, "ビジネス", "ビジネス",
     "彼はビジネスで世界中を飛び回っている。",
     "**He is flying all around the world on business.**",
     [
         E("ビジネス", "noun, \"business.\" From English \"business.\" ビジネスで = \"on business.\" Compounds: ビジネスホテル, ビジネス街. [JLPT N2]"),
         E("世界中（せかいじゅう）", "noun, \"all over the world.\" 世界 + 中 (throughout). The じゅう reading = \"all throughout.\" [JLPT N3]"),
         E("飛び回（とびまわ）っている", "compound verb, 飛ぶ (to fly) + 回る (to go around) = \"to fly around.\" 〜ている indicates habitual action. 飛ぶ (自動詞). [JLPT N2]"),
         E("〜を", "particle, marks the space being traversed. 世界中を飛び回る. [JLPT N5]"),
     ]),
]

batch3 = [
    (811, "キャリア", "キャリア",
     "この仕事はキャリアのある人でないと務まらない。",
     "**This job cannot be handled by someone without career experience.**",
     [
         E("キャリア", "noun, \"career, professional experience.\" From English \"career.\" Accumulated professional track record, not just a career path. キャリアのある人 = \"someone with experience.\" Also means \"carrier\" (telecom), context distinguishes. [JLPT N2]"),
         E("仕事（しごと）", "noun, \"job, work.\" Wago. [JLPT N5]"),
         E("〜でないと", "pattern, \"if not ~ / unless one is ~.\" キャリアのある人でないと = \"unless someone with experience.\" [JLPT N3]"),
         E("務（つと）まらない", "自動詞 務まる（つとまる）negative, \"cannot be handled / is not manageable.\" Counterpart 他動詞: 務める（つとめる）\"to serve in a role.\" [JLPT N2]"),
     ]),
    (812, "ベテラン", "ベテラン",
     "田中さんは教師歴20年のベテランだ。",
     "**Tanaka is a veteran with 20 years of teaching experience.**",
     [
         E("ベテラン", "noun, \"veteran, seasoned professional.\" From French vétéran via English. Someone with long experience in a field. Positive connotation of reliability. [JLPT N2]"),
         E("教師歴（きょうしれき）", "compound noun, \"teaching career / years as teacher.\" 教師 + 歴 (history). Similar: 勤務歴, 運転歴. [JLPT N2]"),
         E("〜のベテランだ", "pattern, \"is a veteran of ~.\" [JLPT N2]"),
     ]),
    (813, "フリー", "フリー",
     "彼はフリー（ランス）のカメラマンをしている。",
     "**He works as a freelance cameraman.**",
     [
         E("フリー", "noun / na-adjective, \"free, freelance.\" From English \"free.\" In employment context, フリーランス specifically means freelance (not \"free of charge\" — that is 無料). [JLPT N2]"),
         E("カメラマン", "noun, \"cameraman, photographer.\" From English \"camera\" + \"man.\" More specific than 写真家（しゃしんか）which implies an artist photographer. [JLPT N2]"),
         E("〜をしている", "pattern, \"to work as (a job).\" [JLPT N4]"),
     ]),
    (814, "エコノミー", "エコノミー",
     "飛行機ではいつもエコノミークラスに乗っている。",
     "**When flying, I always travel in economy class.**",
     [
         E("エコノミー", "noun, \"economy (class).\" From English \"economy.\" In Japanese, almost exclusively for airline economy class. Also: エコノミー症候群 (deep vein thrombosis). Distinct from エコノミクス (economics). [JLPT N2]"),
         E("飛行機（ひこうき）", "kango noun, \"airplane.\" 飛行 + 機. [JLPT N5]"),
         E("クラス", "noun, \"class.\" From English \"class.\" Fare class on an airplane. [JLPT N4]"),
         E("〜に乗っている", "自動詞 乗る（のる）\"to ride\" + 〜ている (habitual). では adds generalizing nuance. [JLPT N5]"),
         E("いつも", "adverb, \"always.\" [JLPT N5]"),
     ]),
    (815, "キャッシュ", "キャッシュ",
     "彼は車の代金をキャッシュで払ったそうだ。",
     "**I heard he paid for the car in cash.**",
     [
         E("キャッシュ", "noun, \"cash.\" From English \"cash.\" Physical money (banknotes/coins), not credit cards. Confusingly, キャッシュカード in Japanese is a bank/ATM card, not a \"cash card.\" [JLPT N2]"),
         E("代金（だいきん）", "kango noun, \"price, payment.\" 代 (price) + 金. 車の代金 = \"payment for the car.\" [JLPT N3]"),
         E("払（はら）ったそうだ", "他動詞 払う（はらう）\"to pay\" past + そうだ (hearsay). Hearsay — speaker heard from someone else. [JLPT N4]"),
         E("〜で", "particle, marks the method of payment. キャッシュで = \"in cash.\" [JLPT N5]"),
     ]),
    (816, "インフレ", "インフレ",
     "インフレで物価が上昇している。",
     "**Prices are rising due to inflation.**",
     [
         E("インフレ", "noun, \"inflation.\" Abbreviation of インフレーション. From English. Rising prices / decreased purchasing power. Opposite: デフレ（デフレーション）\"deflation.\" [JLPT N2]"),
         E("物価（ぶっか）", "kango noun, \"prices (general level).\" 物 (goods) + 価 (price). 物価が上昇する = \"prices are rising.\" [JLPT N2]"),
         E("上昇（じょうしょう）", "kango noun / suru-verb, \"rise, increase.\" 上 (up) + 昇 (rise). More formal than 上がる. [JLPT N2]"),
         E("〜で", "particle, marks cause/reason. インフレで = \"due to inflation.\" [JLPT N5]"),
     ]),
    (817, "デモ", "デモ",
     "増税に抗議して、国のあちこちでデモが行われた。",
     "**Protests were held all over the country against the tax increase.**",
     [
         E("デモ", "noun, \"demonstration, protest.\" Abbreviation of デモンストレーション. In Japanese, exclusively political/social protest — not product demonstration (試演). [JLPT N2]"),
         E("増税（ぞうぜい）", "kango noun, \"tax increase.\" 増 + 税. Common political issue. [JLPT N2]"),
         E("抗議（こうぎ）", "kango noun / suru-verb, \"protest, objection.\" 抗 (resist) + 議 (opinion). 抗議して = \"protesting against.\" [JLPT N2]"),
         E("行（おこな）われた", "他動詞 行う（おこなう）passive, \"was held / conducted.\" Passive focuses on the event, not the organizer. [JLPT N3]"),
         E("あちこち", "noun, \"here and there, various places.\" 国のあちこちで = \"all over the country.\" [JLPT N3]"),
     ]),
    (818, "メーカー", "メーカー",
     "メーカーは海外に工場を持っていることが多い。",
     "**Manufacturers often have factories overseas.**",
     [
         E("メーカー", "noun, \"manufacturer, maker.\" From English \"maker.\" In Japanese business, specifically a manufacturing company. Compounds: 自動車メーカー, 家電メーカー. [JLPT N2]"),
         E("海外（かいがい）", "kango noun, \"overseas, abroad.\" 海 (sea) + 外 (outside). Contrast: 国内. [JLPT N3]"),
         E("工場（こうじょう）", "kango noun, \"factory.\" 工 + 場. [JLPT N4]"),
         E("持っている", "他動詞 持つ（もつ）\"to have, possess\" + 〜ている (state). 工場を持っている = \"owns a factory.\" [JLPT N5]"),
         E("〜ことが多い", "pattern, \"often / it is common that.\" [JLPT N4]"),
     ]),
    (819, "システム", "システム",
     "今、教育システムの見直しが進んでいる。",
     "**Reform of the education system is currently underway.**",
     [
         E("システム", "noun, \"system.\" From English \"system.\" Organizational systems, computer systems, institutional structures. [JLPT N2]"),
         E("教育（きょういく）", "kango noun, \"education.\" 教 (teach) + 育 (nurture). [JLPT N4]"),
         E("見直し（みなおし）", "verbal noun, \"reexamination, review.\" 見直す = 見る + 直す (to redo) = \"to review / reconsider.\" Strong collocation: システムの見直し. [JLPT N2]"),
         E("進（すす）んでいる", "自動詞 進む（すすむ）\"to advance, progress\" + 〜ている (ongoing). Counterpart 他動詞: 進める（すすめる）. [JLPT N3]"),
     ]),
    (820, "ケース", "ケース",
     "指輪をケースにしまった。",
     "**I put the ring in its case.**",
     [
         E("ケース", "noun, \"case, container, box.\" From English \"case.\" Small container for storing items. Also abstract: このケースでは = \"in this case (situation).\" [JLPT N2]"),
         E("指輪（ゆびわ）", "kango noun, \"ring (finger).\" 指 (finger) + 輪 (ring). Wago reading despite kanji. [JLPT N3]"),
         E("しまった", "他動詞 しまう \"to put away, store\" past. Implies careful/tidy storage. Distinct from 置く — しまう means putting in its proper place. [JLPT N3]"),
         E("〜に", "particle, marks the destination. ケースに = \"into the case.\" [JLPT N5]"),
     ]),
]

batch4 = [
    (821, "パターン", "パターン",
     "血液型性格占いは、人間の性格を四つのパターンに分けている。",
     "**Blood type personality dividers classify human personality into four patterns.**",
     [
         E("パターン", "noun, \"pattern, type, category.\" From English \"pattern.\" Recurring types or models. 四つのパターン = \"four patterns/types.\" [JLPT N2]"),
         E("血液型（けつえきがた）", "kango noun, \"blood type.\" 血液 + 型. Blood type personality theory is popular but unproven in Japan. [JLPT N3]"),
         E("性格（せいかく）", "kango noun, \"personality, character.\" 性 (nature) + 格. For Chinese speakers: similar to Chinese 性格 but used slightly differently. [JLPT N4]"),
         E("占い（うらない）", "noun, \"fortune-telling, divination.\" 占う nominalized. 血液型性格占い = blood type personality fortune-telling. [JLPT N2]"),
         E("人間（にんげん）", "kango noun, \"human being.\" 人 + 間. [JLPT N4]"),
         E("〜に分（わ）けている", "他動詞 分ける（わける）\"to divide, separate\" + 〜ている (ongoing). Counterpart 自動詞: 分かれる（わかれる）. 〜に分ける = \"to divide into X categories.\" [JLPT N4]"),
     ]),
    (822, "プラン", "プラン",
     "両親は、定年後に海外移住するプランを立てている。",
     "**My parents are making a plan to emigrate overseas after retirement.**",
     [
         E("プラン", "noun, \"plan.\" From English \"plan.\" Interchangeable with 計画（けいかく）but more casual. プランを立てる = \"to make a plan.\" [JLPT N2]"),
         E("両親（りょうしん）", "kango noun, \"both parents.\" 両 (both) + 親. More formal than お父さんとお母さん. [JLPT N4]"),
         E("定年（ていねん）", "kango noun, \"retirement age.\" 定 (fixed) + 年. Traditionally 60, now often 65 in Japan. [JLPT N2]"),
         E("海外移住（かいがいいじゅう）", "kango compound, \"emigration overseas.\" 海外 + 移住 (relocation). 移 (move) + 住 (dwell). [JLPT N2]"),
         E("プランを立てている", "collocation, \"to make/form a plan.\" 立てる（たてる）他動詞 = \"to formulate.\" Counterpart 自動詞: 立つ（たつ）. 〜ている = planning in progress. [JLPT N3]"),
     ]),
    (823, "トラブル", "トラブル",
     "テレビの音のことでアパートの隣人とトラブルになった。",
     "**I got into a dispute with my apartment neighbor over the TV sound.**",
     [
         E("トラブル", "noun, \"trouble, dispute, problem.\" From English \"trouble.\" Often refers to interpersonal conflicts. トラブルになる = \"to get into a dispute.\" More specific than 問題 for interpersonal friction. [JLPT N2]"),
         E("音（おと）", "noun, \"sound, noise.\" Here: TV sound bothering the neighbor. [JLPT N5]"),
         E("アパート", "noun, \"apartment.\" From English \"apartment.\" In Japanese, usually a modest, often wooden apartment building (vs. マンション = upscale concrete condominium). [JLPT N4]"),
         E("隣人（りんじん）", "kango noun, \"neighbor.\" 隣 (next to) + 人. More formal than 隣の人. [JLPT N2]"),
         E("〜とトラブルになった", "pattern, \"to get into a dispute with X.\" と marks the other party. [JLPT N2]"),
     ]),
    (824, "エラー", "エラー",
     "このデジカメはよくエラーが起こる。",
     "**This digital camera frequently has errors.**",
     [
         E("エラー", "noun, \"error, malfunction.\" From English \"error.\" Technical/computer errors, machine malfunctions, sports errors (baseball). エラーが起こる = \"an error occurs.\" [JLPT N2]"),
         E("デジカメ", "abbreviation, \"digital camera.\" デジタルカメラ shortened. Very common in speech. [JLPT N2]"),
         E("よく", "adverb, \"often, frequently.\" Here: frequency (not \"well\"). [JLPT N5]"),
         E("起こ（おこ）る", "自動詞, \"to occur, happen.\" Counterpart 他動詞: 起こす（おこす）\"to cause.\" エラーが起こる = error occurs on its own. [JLPT N4]"),
     ]),
    (825, "クレーム", "クレーム",
     "「買った肉が変なにおいがする」と、スーパーにクレームがあった。",
     "**There was a complaint to the supermarket: \"The meat I bought smells strange.\"**",
     [
         E("クレーム", "noun, \"complaint, claim.\" From English \"claim\" but in Japanese means specifically \"complaint.\" Semantic shift: English \"claim\" = demand/assertion; Japanese クレーム = 投诉/抱怨. クレームをつける = to make a complaint. [JLPT N2]"),
         E("変（へん）", "na-adjective, \"strange, odd, weird.\" 変なにおい = \"strange smell.\" [JLPT N4]"),
         E("におい", "noun, \"smell, odor.\" Can be 匂い. Often for unpleasant smells (vs. 香り・かおり = pleasant fragrance). [JLPT N3]"),
         E("〜がする", "pattern, \"to make (a smell/sound/taste).\" Sensory perception. 変なにおいがする = \"to have a strange smell.\" [JLPT N4]"),
         E("スーパー", "noun, \"supermarket.\" Abbreviated from スーパーマーケット. [JLPT N5]"),
         E("〜にクレームがあった", "pattern, \"there was a complaint to X.\" に marks the recipient. [JLPT N2]"),
     ]),
    (826, "キャンセル", "キャンセル",
     "ホテルの予約をキャンセルした。",
     "**I canceled the hotel reservation.**",
     [
         E("キャンセル", "noun / suru-verb, \"cancellation, to cancel.\" From English \"cancel.\" Very common for canceling reservations, orders, appointments. キャンセル料 (cancellation fee). [JLPT N2]"),
         E("予約（よやく）", "kango noun, \"reservation, booking.\" 予 (pre-) + 約 (promise). 予約をキャンセルする = \"to cancel a reservation.\" [JLPT N3]"),
         E("ホテル", "noun, \"hotel.\" From English \"hotel.\" [JLPT N5]"),
         E("〜をキャンセルした", "pattern, \"canceled X.\" [JLPT N2]"),
     ]),
    (827, "ストップ", "ストップ",
     "踏切事故で電車が1時間ストップした。",
     "**The train stopped for one hour due to a railway crossing accident.**",
     [
         E("ストップ", "noun / suru-verb, \"stop, to stop.\" From English \"stop.\" For sudden/unexpected stops (trains, machines). More dramatic than 止まる（とまる）— implies a complete halt. [JLPT N2]"),
         E("踏切（ふみきり）", "noun, \"railway crossing.\" 踏む (step on) + 切り (cut across). Standard term for a level crossing. [JLPT N2]"),
         E("事故（じこ）", "kango noun, \"accident.\" [JLPT N4]"),
         E("電車（でんしゃ）", "kango noun, \"train (electric).\" 電 + 車. In Japan, specifically electric commuter trains. [JLPT N5]"),
         E("〜で", "particle, marks cause. 踏切事故で = \"due to a crossing accident.\" [JLPT N5]"),
     ]),
    (828, "カット", "カット",
     "ケーキを八つにカットした。",
     "**I cut the cake into eight pieces.**",
     [
         E("カット", "noun / suru-verb, \"to cut.\" From English \"cut.\" For cutting physical objects (hair, food, film scenes). ヘアカット (haircut). [JLPT N2]"),
         E("ケーキ", "noun, \"cake.\" From English \"cake.\" [JLPT N5]"),
         E("八（やっ）つ", "counter, \"eight (pieces).\" General counter. 八つにカットする = \"cut into eight pieces.\" に marks the result of division. [JLPT N5]"),
     ]),
    (829, "カバー", "カバー",
     "ソファーをカバーで覆う。",
     "**Cover the sofa with a cover.**",
     [
         E("カバー", "noun / suru-verb, \"cover, to cover.\" From English \"cover.\" As noun: protective cover for furniture/books/phones. As verb: cover physically or figuratively. Also: カバーソング (cover song). [JLPT N2]"),
         E("ソファー", "noun, \"sofa, couch.\" From English \"sofa.\" Also ソファ (without long vowel). [JLPT N4]"),
         E("覆（おお）う", "他動詞, \"to cover, cover over.\" Counterpart 自動詞: 覆われる (passive). More literary than 被せる（かぶせる）. [JLPT N2]"),
         E("〜を〜で覆う", "pattern, \"to cover X with Y.\" を marks what is covered, で marks the covering material. [JLPT N2]"),
     ]),
    (830, "リハビリ", "リハビリ",
     "骨折で入院し、退院後もしばらくリハビリのため病院に通った。",
     "**I was hospitalized for a bone fracture and continued going to the hospital for rehabilitation for a while after discharge.**",
     [
         E("リハビリ", "noun, \"rehabilitation.\" Abbreviation of リハビリテーション. From English. Physical therapy and recovery exercises after injury/surgery. [JLPT N2]"),
         E("骨折（こっせつ）", "kango noun, \"bone fracture.\" 骨 (bone) + 折 (break). [JLPT N2]"),
         E("入院（にゅういん）", "kango noun / suru-verb, \"hospitalization.\" 入 (enter) + 院 (institution). [JLPT N3]"),
         E("退院（たいいん）", "kango noun, \"discharge from hospital.\" 退 (leave) + 院. Opposite of 入院. 退院後 = \"after discharge.\" [JLPT N2]"),
         E("通（かよ）った", "自動詞 通う（かよう）\"to commute, go regularly\" past. Used for repeated visits (hospital, school, work). [JLPT N3]"),
         E("〜し、〜", "conjunctive form, \"and / then.\" Lists sequential events. 入院し = \"was hospitalized, and then...\" [JLPT N4]"),
     ]),
]

batch5 = [
    (831, "プレッシャー", "プレッシャー",
     "この仕事は、新入社員にはプレッシャーが大きい。",
     "**This job puts a lot of pressure on new employees.**",
     [
         E("プレッシャー", "noun, \"pressure, stress.\" From English \"pressure.\" In Japanese, psychological pressure from work/responsibility — not physical pressure (圧力・あつりょく). プレッシャーが大きい = \"a lot of pressure.\" [JLPT N2]"),
         E("新入社員（しんにゅうしゃいん）", "kango compound, \"new employee, new hire.\" 新 (new) + 入 (enter) + 社員. In Japan, specifically fresh graduates entering a company (typically April). [JLPT N2]"),
         E("〜には", "particle, \"for X.\" に marks the person affected, は topicalizes. [JLPT N5]"),
         E("大きい（おおきい）", "i-adjective, \"big, large, great.\" Modifies the magnitude of pressure. [JLPT N5]"),
         E("〜が大きい", "pattern, \"X is large/great.\" プレッシャーが大きい = \"the pressure is considerable.\" [JLPT N4]"),
     ]),
    (832, "カウンセリング", "カウンセリング",
     "学校で子どもたちにカウンセリングする仕事をしている。",
     "**I work in a job counseling children at school.**",
     [
         E("カウンセリング", "noun / suru-verb, \"counseling.\" From English \"counseling.\" Psychological counseling, career counseling, professional guidance. カウンセラー does カウンセリング. [JLPT N2]"),
         E("学校（がっこう）", "kango noun, \"school.\" [JLPT N5]"),
         E("〜にカウンセリングする", "pattern, \"to counsel X.\" に marks the recipient. 他動詞 usage. [JLPT N2]"),
         E("〜仕事をしている", "pattern, \"to work in a job that does X.\" [JLPT N4]"),
     ]),
    (833, "キャラクター", "キャラクター",
     "彼はちょっと変わったキャラクターの持ち主だ。",
     "**He is someone with a rather unusual character/personality.**",
     [
         E("キャラクター", "noun, \"character, personality.\" From English \"character.\" Used for both fictional characters and a person's personality type. Here: personality sense. ちょっと変わったキャラクター = \"a somewhat unusual personality.\" [JLPT N2]"),
         E("ちょっと", "adverb, \"a bit, somewhat.\" Softens the description. [JLPT N5]"),
         E("変わ（かわ）った", "連体形 of 変わる（かわる）自動詞 \"to change,\" used as adjective meaning \"unusual, eccentric.\" Semantic drift: past participle form became an adjective meaning \"odd.\" [JLPT N4]"),
         E("持（も）ち主（ぬし）", "noun, \"owner, person who has (a quality).\" 持つ + 主 (owner). キャラクターの持ち主 = \"a person who has that character type.\" [JLPT N2]"),
     ]),
    (834, "ユニーク", "ユニークな",
     "彼女はユニークな性格だ。",
     "**She has a unique personality.**",
     [
         E("ユニーク（な）", "na-adjective, \"unique, distinctive, one-of-a-kind.\" From English \"unique.\" In Japanese, generally positive — interesting and original. For Chinese speakers: closer to 独特的/有个性的 rather than 唯一的. [JLPT N2]"),
         E("性格（せいかく）", "kango noun, \"personality, character.\" [JLPT N4]"),
     ]),
    (835, "ルーズ", "ルーズな",
     "あの人は時間にルーズだ。",
     "**That person is lax about time / always late.**",
     [
         E("ルーズ（な）", "na-adjective, \"lax, loose, careless (about rules/time).\" From English \"loose.\" Almost always negative — sloppy about punctuality, rules, discipline. 時間にルーズ = \"not punctual.\" Opposite: 時間に厳しい. For Chinese speakers: more like 散漫/不严谨 than 松弛. [JLPT N2]"),
         E("あの人（ひと）", "phrase, \"that person.\" Can carry a slightly dismissive tone. [JLPT N5]"),
         E("〜にルーズだ", "pattern, \"to be lax/careless about X.\" に marks the domain. Other collocations: お金にルーズ, ルールにルーズ. [JLPT N2]"),
     ]),
    (836, "ロマンチック", "ロマンチックな",
     "デートをするならロマンチックな場所がいい。",
     "**If we are going on a date, I would prefer a romantic place.**",
     [
         E("ロマンチック（な）", "na-adjective, \"romantic.\" From English \"romantic.\" Describes atmospheres, settings, or situations evoking romantic feelings. Related: ロマン (romance/dreamy feeling). [JLPT N2]"),
         E("デート", "noun, \"date (romantic).\" From English \"date.\" デートをする = \"to go on a date.\" [JLPT N4]"),
         E("場所（ばしょ）", "kango noun, \"place, location.\" 場 + 所. [JLPT N4]"),
         E("〜なら〜がいい", "pattern, \"if X, then Y is good / I prefer Y.\" なら conditional; 〜がいい expresses preference. [JLPT N4]"),
     ]),
    (837, "センス", "センス",
     "彼女はいつもセンスのいい服を着ている。",
     "**She always wears clothes with good taste.**",
     [
         E("センス", "noun, \"sense, taste, flair.\" From English \"sense.\" In Japanese, specifically aesthetic sense — fashion, design, etc. センスがいい = \"has good taste.\" [JLPT N2]"),
         E("服（ふく）", "noun, \"clothes, clothing.\" Wago. [JLPT N5]"),
         E("着（き）ている", "他動詞 着る（きる）\"to wear (upper body garments)\" + 〜ている (state/habitual). For Chinese speakers: 着る is for upper-body only (vs. 履く for footwear, 被る for hats). [JLPT N5]"),
         E("センスのいい", "pattern, \"with good taste / tasteful.\" の connects センス to いい, forming an attributive phrase modifying 服. [JLPT N2]"),
     ]),
    (838, "エコロジー", "エコロジー",
     "最近は、どの国でもエコロジーの考え方が当たり前になった。",
     "**Recently, ecological thinking has become commonplace in every country.**",
     [
         E("エコロジー", "noun, \"ecology, environmental awareness.\" From English \"ecology.\" Often shortened to エコ. Broadly used for environmental consciousness. エコカー, エコバッグ. [JLPT N2]"),
         E("最近（さいきん）", "kango noun, \"recently, lately.\" 最 (most) + 近 (near). [JLPT N4]"),
         E("どの国でも", "phrase, \"in every country / no matter which country.\" どの = \"which (of all).\" でも = \"even / in any.\" [JLPT N4]"),
         E("考え方（かんがえかた）", "noun, \"way of thinking, mindset.\" 考える + 方 (way/method). [JLPT N3]"),
         E("当たり前（あたりまえ）", "na-adjective, \"natural, obvious, commonplace.\" 当り (hit) + 前 (front) — originally \"what one would expect.\" Semantic drift: \"expected\" → \"normal/commonplace.\" [JLPT N3]"),
         E("〜になった", "pattern, \"has become ~.\" 当たり前になった = \"has become commonplace.\" [JLPT N5]"),
     ]),
    (839, "ダム", "ダム",
     "山奥にダムが建設された。",
     "**A dam was constructed deep in the mountains.**",
     [
         E("ダム", "noun, \"dam.\" From English \"dam.\" Large water-retaining structures built in mountains for flood control, water supply, hydroelectric power. [JLPT N2]"),
         E("山奥（やまおく）", "noun, \"deep in the mountains, remote mountain area.\" 山 + 奥 (interior). おく is wago reading. Far from civilization. [JLPT N2]"),
         E("建設（けんせつ）", "kango noun / suru-verb, \"construction, building.\" 建 (build) + 設 (establish). More formal than 建てる. [JLPT N3]"),
         E("された", "passive past of する, \"was done.\" 建設された = \"was constructed.\" The dam is the recipient of the action. [JLPT N3]"),
         E("〜に", "particle, marks the location. 山奥に = \"in the deep mountains.\" [JLPT N5]"),
     ]),
    (840, "コンクリート", "コンクリート",
     "この壁はコンクリートでできている。",
     "**This wall is made of concrete.**",
     [
         E("コンクリート", "noun, \"concrete.\" From English \"concrete.\" Standard term in Japanese construction. Often abbreviated to コンクリ. コンクリート造り（づくり）= \"concrete construction.\" [JLPT N2]"),
         E("壁（かべ）", "noun, \"wall.\" Wago. [JLPT N5]"),
         E("できている", "自動詞 できる \"to be made of, to be composed of\" + 〜ている (state). できる has many meanings (can do, be completed, be made of) — here \"to be made of.\" No 他動詞 counterpart for this meaning. [JLPT N4]"),
         E("〜でできている", "pattern, \"is made of X.\" で marks the material. [JLPT N4]"),
     ]),
]

# Combine all batches
all_entries = entries + batch2 + batch3 + batch4 + batch5

# Build output
output = []
for index, word, yomi, sentence, translation, notes in all_entries:
    parts = [translation, "", "---", ""]
    for note_tuple in notes:
        label = note_tuple[0]
        definition = note_tuple[1]
        parts.append(f"- **{label}** — {definition}")
    explanation = "\n".join(parts)
    output.append({"index": index, "explanation": explanation})

# Write JSON
outpath = os.path.join("output", "explanations_unit09_all.json")
with open(outpath, "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"Unit 9: wrote {len(output)} explanations")
